### PR TITLE
Add nicer logging

### LINKED ISSUE #1: Better console output
Probably should add chalk back in and make it look better, like actual parcel, or the parcel-compress-plugin

### PR DESCRIPTION
**Pull request by lukechilds**
Resolves #1 

I tried to mimic the default parcel logging as close as possible:

<div align="center">

</div>

### CODE REVIEW

**Comment by ABuffSeagull** [comment]
Man, you're on fire. Again, thank you so much.

**Comment by ABuffSeagull** [comment]
I'm reworking the packaging (using [@pika/pack](https://www.pikapkg.com/blog/introducing-pika-pack/)), so I'll publish this after I get it working.

**Comment by lukechilds** [comment]
Nice, I'm not familiar with pika pack, looks cool.

**Comment by ABuffSeagull** [comment]
Just kidding, it won't work :laughing: I'll publish this then

**Pull request merged**
